# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19ef21b6c67dcf8f98231e1d5670a966d639b5e33c65eb99d3960be817d14fc3ab291870d677051c32ec9563878cd3dbb763215ed5912cae82074f4da5df1369

test:
  secret_key_base: eb53f94f8ae93cb908811d2513b0c15dae07e009eb4a3ed85967708ad08b9c6cc02d683ec8af333965eadf4359227bea683c1a2d390c0522f01ad69780edabde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
